language: java
dist: trusty
sudo: false

matrix:
  include:
    - name: "Java 7 Tests"
      jdk: openjdk7
      env: TESTENV="test"
    - name: "Java 8 Tests"
      jdk: oraclejdk8
      env: TESTENV="test"
    - name: "Coverage"
      jdk: oraclejdk8
      env: TESTENV="cover"

script:
  - '[ "$TESTENV" == "test" ] && mvn clean test; true'
  - '[ "$TESTENV" == "cover" ] && mvn clean cobertura:cobertura; true'

after_success:
  - '[ "$TESTENV" == "cover" ] && bash <(curl -s https://codecov.io/bash); true'
